### ISSUE TITLE
Cheers and thanks for all the (py)fish

### ISSUE THREAD

**Issue by thogar-computer** [PierrotVdAa/PyFish#8]
@Ezhen @PierrotVdAa @everardo-geomar @Edclarkoi

Great working with you guys. If you ever need help with getting BODC/NOC data or you want to submit data to us :) 
Give me a shout 

thogar@noc.ac.uk

**Comment by everardo-geomar** [comment]
thanks Thomas!

Let me know if any of you is around Kiel! if you want to collaborate on a software project I'm all ears!

egonzalez@geomar.de

**Comment by Ezhen** [comment]
Thanks Thomas,

It was a pleasure to work with you guys,

You can contact me if you ever need help with COAWST ocean model or for 
collaboration on the wind farms biogeochemstry & sedimentology.

Evgeny

**Comment by PierrotVdAa** [comment]
Thanks to all of you. It was indeed a pleasure to work on this project together. I hope to see you again in the future.

If you ever need any biology or phylogeny advice, just let me know.

pvderaa@vub.be
